Adds more window title options
Jas-SinghFSU/HyprPanel pull request #169
Opened 2024-08-22 14:34 UTC by painerp

Adds multiple new window title options:
- A toggle for the Icon in custom titles
- A toggle for the Custom Window Title (if toggled off I added a default title that uses the title given by the client or if this empty fallsback to the class name)
- Truncation toggle and size options for the new default title

2024-08-27 04:46 UTC, Jas-SinghFSU commented
Noticed the following issues:
1. Show Custom Title hides the icon (even with icon enabled)
2. Truncate window title doesn't seem to work (enabled or disabled, no matter the truncation size)

2024-08-28 23:51 UTC, painerp commented
Oh my bad, I might have broken something while merging your changes. I will look at them in a few days when I find some more time.

2024-08-29 03:26 UTC, Jas-SinghFSU commented
No worries :+1:

2024-09-05 05:35 UTC, painerp commented
@Jas-SinghFSU Alright I finally got some time on my hands again and checked your issues.
1. Added custom icon support even when the custom title is disabled.
2. Applied truncation to custom titles as well.

I hope I understood your points correctly, else just give me heads up and i will fix it. Thanks!

2024-09-07 04:20 UTC, Jas-SinghFSU requested changes

2024-09-07 04:20 UTC, Jas-SinghFSU commented on modules/bar/window_title/index.ts
> +    return title;
```suggestion
    let title = client.title;
    // If the title is empty or only filled with spaces, fallback to the class name
    if (title.length === 0 || title.match(/^ *$/)) {
        title = client.class;
    }
    return title;
```
We return class by default for windows. I don't necessarily dislike having the title as well but if we're going to display a title we should make that an option instead.

Everything else looks great :+1:

2024-09-08 20:08 UTC, Jas-SinghFSU approved these changes
Lookin' juicy :+1:

2024-09-08 20:09 UTC, Jas-SinghFSU commented
As always, appreciate the contribution :heart:

2024-09-08 20:09 UTC, merged