Add install instructions for Fedora
Jas-SinghFSU/HyprPanel pull request #260
Opened 2024-09-15 07:34 UTC by tijptjik

2024-09-15 23:50 UTC, smathles commented
Great to see another Fedora enjoyer! I have actually also done a similar project on a personal repo that I've never made a PR for [link](https://github.com/smathles/HyprPanelSmathles/edit/master/README.md). I see some things you implemented that I either missed or did more efficiently than I did (grimblast using the copr repo and I missed bluez-tools).

I note we had different approaches to install sass and matugen: 
- I used `sudo dnf install nodejs; sudo npm install -g sass` where you had `bun install -g sass`. As we should already have bun installed, I prefer your way. 
- For matugen, I used [this copr repo](https://copr.fedorainfracloud.org/coprs/heus-sueh/packages/package/matugen/), as it was up to date with the latest matugen and install size is only 9.6M as opposed to installing cargo first and using it to install matugen (250M if you don't already have rust/cargo packages installed). Of course, using copr repos comes with the risk that one day it may not be maintained (just like the AUR), so depends on what @Jas-SinghFSU's preference is there. Slight caveat to this method is that this copr repo also packages swww... so it would be best to install everything else from the first repo first and then enable this one and install matugen to avoid any package ambiguity (FYI I did this and it works fine on my system. Would you be able to try it and see if there's any conflicts?).

Additionally I think the optional python/gpustat/pywal section is missing? I know not everyone might want it but it's still good to put down explicitly imo.

2024-09-16 00:09 UTC, smathles commented on README.md
> +```bash
Add sudo to the dnf install instructions

2024-09-16 00:11 UTC, smathles commented on README.md
> +```
Optionally remove cargo section and change dnf section to:
> DNF - with solopasha's [hyprland COPR](https://copr.fedorainfracloud.org/coprs/solopasha/hyprland/) and heus-sueh's [matugen COPR](https://copr.fedorainfracloud.org/coprs/heus-sueh/packages/packages/)
```bash
dnf copr enable solopasha/hyprland
dnf install pipewire libgtop2 bluez bluez-tools grimblast hyprpicker btop NetworkManager cargo wl-clipboard swww brightnessctl gnome-bluetooth aylurs-gtk-shell
dnf copr enable heus-sueh/packages
sudo dnf install matugen
```
Subject to testing + @Jas-SinghFSU's preference.

2024-09-16 00:11 UTC, smathles commented on README.md
> +cargo install matugen
Optional: see previous comment

2024-09-16 00:16 UTC, smathles requested changes
Some changes I think would be good (add python section), others are very subjective (get @Jas-SinghFSU to approve). Interested to hear your thoughts :pray:

2024-09-16 00:16 UTC, smathles commented on README.md
> +
Requesting to add:

> Python (Optional):
> ```bash
> sudo dnf install python python3-pip; pip install gpustat pywal
> ```

2024-09-16 00:16 UTC, smathles commented on README.md
> +```
Optionally remove cargo section and change dnf section to:
> DNF - with solopasha's [hyprland COPR](https://copr.fedorainfracloud.org/coprs/solopasha/hyprland/) and heus-sueh's [matugen COPR](https://copr.fedorainfracloud.org/coprs/heus-sueh/packages/packages/)
```bash
dnf copr enable solopasha/hyprland
dnf install pipewire libgtop2 bluez bluez-tools grimblast hyprpicker btop NetworkManager cargo wl-clipboard swww brightnessctl gnome-bluetooth aylurs-gtk-shell
dnf copr enable heus-sueh/packages
sudo dnf install matugen
```
Subject to testing + @Jas-SinghFSU's preference.

2024-09-16 00:16 UTC, smathles commented on README.md
> +dnf copr enable solopasha/hyprland
Add `sudo` to the dnf and flatpak install instructions to be consistent with arch install instructions (yay doesn't need sudo).

2024-09-16 00:21 UTC, smathles commented
Ooh wait missed one. `gvfs` is now a dependency as well (recentish commit) so that should be added to the dnf install list (yes, it's in the fedora repos, no stress).

2024-09-16 05:52 UTC, tijptjik commented
Great! Thanks for the feedback @smathles! I've made the following changes after syncing with `HEAD` on `master` :

- Add subsection for `COPR` setup
- Add Priority to `solopasha/hyprland` to avoid conflicts in the `swww` package.
- Remove `cargo` from DNF instructions
- Remove `cargo` instructions
- Add `power-profiles-daemon and `gvfs` to DNF instructions
- Add requested python instructions
- Add `sudo` to the commands

2024-09-16 06:57 UTC, smathles commented
Looks awesome. Absolutely nothing I'd change!

@Jas-SinghFSU are you happy with the way this looks in the README.md file? I know you'll also have to update your webpage for the wiki at some point. 

Looks great to me though.

2024-09-16 09:08 UTC, Jas-SinghFSU commented
Lgtm

2024-09-16 09:08 UTC, merged

2024-09-16 09:09 UTC, Jas-SinghFSU commented
Ty for the contribution :heart: