Add Application Launcher
Jas-SinghFSU/HyprPanel pull request #685
Opened 2024-12-31 18:19 UTC by Aetherall

### Hi ! I discovered hyprpanel today and besides the app launcher it really does it all for me !

So I am proposing my help to add an optional one ( I will surely contribute some more features in the future )

For now this is a really crude draft of an application launcher menu ( dropdown & popup )

it is my first time using gtk and astal and surely made a lot of mistakes. 
I couldnt make keyboard navigation work, even trying to use the Gtk3 ListBox and ListBoxRow.

Also I didnt do any styling for now and just reused notification menu styles.

PS:
- do you guys have live reload in development ?
- is the .js extensions in imports mandatory for the code to build and the lsp to work in your system ? On my system it breaks (nix flakes) because astal pulled as typescript sources and only compiled along with hyperpanel so not resolvable in dev. Removing the .js extensions on astal package does fix it for me.
- is a gtk4 migration planned ? I can contribute on that too to keep up with astal :)

Thanks for this awesome project !
Happy new year !

2024-12-31 18:29 UTC, Aetherall commented
My issue with imports seems to have be solved today, i'll rebase tomorrow :)

2025-02-24 23:51 UTC, idea90 requested changes
MERGE NOW Or else

2025-02-25 00:14 UTC, Jas-SinghFSU commented
> MERGE NOW Or else

U wot m8?

2025-02-25 00:15 UTC, Jas-SinghFSU commented
Solid draft but we definitely want to flesh it out more and make it customizable. I'll look into it.

2025-02-25 14:57 UTC, Aetherall commented
> MERGE NOW Or else

Please be my guest, if you want to branch off this PR and finish it.
You can also start a bounty issue if you want someone to do it for you

@Jas-SinghFSU thanks a lot :)

I noted some points not to overlook:
- [ ] Keyboard support for arrow keys and / hjkl
- [ ] Reset search string variable on open 
  _i dont know the lifecycle of the underlying gtk resource, so it may be safer to do it while we know it is instanciated for sure_
- [ ] Integration with the styling system
- [ ] Tuning of the search ponderation, feels pretty useless right now besides for the 1st result
- [ ] Challenge the helper functions used, they resemble patterns i'm familiar with, but may not be good practices for ags/astal nor align with rest of the codebase.

Don't hesitate to share a todo if you find the time to look into it but not to implement the changes, so I may help during my next vacations ( idk when yet )

2025-03-01 21:14 UTC, Jas-SinghFSU commented
@Aetherall Awesome, sounds good. I'm closing this one for now but if you're interested in discussing the direction of the launcher you're most welcomed to join us in the `#dev` channel on discord :).

2025-03-01 21:14 UTC, closed without merging

2025-04-03 00:04 UTC, plasmoduck commented
Here is the code from the ags developer. Someone thst knows what they are doing could literally add this into hype panel in like 30 minutes max. 

https://github.com/Aylur/astal/tree/main/examples%2Fgtk3%2Fjs%2Fapplauncher